# Generated by Django 4.2.7 on 2025-10-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
