# Generated by Django 4.2.7 on 2025-10-18 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0002_alter_course_semester_alter_section_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='section',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='scheduler_app.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='sections_teaching', to='scheduler_app.instructor'),
        ),
    ]
