# Generated by Django 4.2.7 on 2025-10-18 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0003_remove_course_department_remove_course_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='scheduler_app.section'),
        ),
    ]
