# Generated by Django 4.2.7 on 2025-12-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0008_section_room_alter_meetingtime_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingtime',
            options={'ordering': ['pid']},
        ),
    ]
