# Generated by Django 4.2.7 on 2025-12-08 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0009_alter_meetingtime_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_id', 'department')},
        ),
    ]
