# Generated by Django 4.2.7 on 2025-12-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0012_add_course_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['department__name', 'course_name']},
        ),
    ]
