# Generated by Django 4.2.7 on 2025-12-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0014_auto_20251210_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='fitness_progression',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
